### PR TITLE
Power API re-write. I don't know it's working or not, but it doesn't …

### PR DESCRIPTION
**Pull request by Dragon2488**
…break anything with 100% chance.

### CODE REVIEW

**Comment by Dragon2488** [comment]
Or with 90% chance

**Comment by modmuss50** [comment]
I will need to test it

**Comment by modmuss50** [comment]
Could you make the PR to allow TechReborn to work with this?

**Comment by Dragon2488** [comment]
PR?

**Comment by Dragon2488** [comment]
I'll rewrite TechReborn to use this when version of RebornCore with this commit will be on maven. This commit keeps backward capability with current version of TechReborn.

**Comment by Dragon2488** [comment]
Can you merge it already?

**Comment by modmuss50** [comment]
I will once i have had a look at it.

**Comment by modmuss50** [comment]
Might want to bump the version number as well

**Comment by Dragon2488** [comment]
Lol, no, it breaks current TechReborn because of different method name.

**Pull request merged**
