### PR TITLE
quick NPE fix

### PR DESCRIPTION
**Pull request by shadoxxhd**
add handling in case getCurrentLanguage returns null

### CODE REVIEW

**Comment by modmuss50** [comment]
Please can you confirm this happening on the latest forge? this should also be fixed as Grum said it has been hotfixed on mojangs end.

**Comment by shadoxxhd** [comment]
This happened because of a change in the .lang files. Forge update might fix this.

**Comment by shadoxxhd** [comment]
I still hear complaints about the issue, so I doubt mojang fixed it properly...
EDIT: nvm, someone just said it magically began working again.

**Comment by modmuss50** [comment]
There has been a forge update, and a fix on mojang's end see: 

https://github.com/MinecraftForge/MinecraftForge/pull/5105

I don't think this PR will help tbh, as it will take.

**Comment by shadoxxhd** [comment]
Even if forge fixes this, a NPE check might be useful in case someone changes language format again.

**Comment by modmuss50** [comment]
closing, as forge and mojang have both pushed a fix out. Mods should not be fixing issues like this, and there may be other places in our codebase that is effected if this happens again. Sorry for the inconvenience.

**Pull request closed without merging**
