### PR TITLE
Add implementations in ExternalPowerSystems for chargeItem and requestEnergyFromArmor

### PR DESCRIPTION
**Pull request by coderbot16**
Looks like I forgot these in the previous PR. Convenience functions in line with the other implementations provided in ExternalPowerSystems.

### CODE REVIEW

**Comment by modmuss50** [comment]
Is it worth checking ExternalPowerManager.isPoweredItem before charging the item?

Would be quite easy to add and may save some time / prevent issues if not checked in the ExternalPowerManager

**Comment by coderbot16** [comment]
Seems easy enough, I can add that. Would avoid potential bugs in other ExternalPowerManager implementations.

**Comment by coderbot16** [comment]
Alright, I added checks to dischargeItem and chargeItem. I didn't add any checks to requestEnergyFromArmor since the manager is responsible for finding and discharging the items itself, and ExternalPowerSystems doesn't know what items the implementation will be drawing energy from.

**Comment by coderbot16** [comment]
Also, I'll keep the isPoweredItem checks in the ExternalPowerManager implementations since it is possible to access them without going through ExternalPowerSystems methods.

**Comment by modmuss50** [comment]
Logic looks good, how ever this can be done in a cleaner way using `filter`

Here is an example:

```java
public static void chargeItem(TilePowerAcceptor tilePowerAcceptor, ItemStack stack){
	externalPowerHandlerList.stream()
		.filter(externalPowerManager -> externalPowerManager.isPoweredItem(stack))
		.forEach(externalPowerManager -> externalPowerManager.chargeItem(tilePowerAcceptor, stack));
}
```

**Comment by coderbot16** [comment]
Ah yes, I probably should have done that since I'm already used to the Rust iterator APIs :P - will fix

**Comment by coderbot16** [comment]
Alright, the checks now properly utilize Stream::filter.

**Comment by modmuss50** [comment]
Looks good, thanks

**Pull request merged**
